import fs from 'fs';
import path from 'path';
import { query } from './db.js';

const STORAGE_DIR = process.env.STORAGE_DIR || './storage';
const WORKER_INTERVAL_MS = Math.max(1000, Number(process.env.WORKER_INTERVAL_MS || 2500));
const WORKER_BATCH_SIZE = Math.max(1, Number(process.env.WORKER_BATCH_SIZE || 4));
const RETRY_DELAY_MS = 10000;

let timer = null;
let busy = false;

function storagePath(...parts) {
  return path.join(STORAGE_DIR, ...parts);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

async function emitJobEvent(storyId, jobId, type, message, payload = {}) {
  await query(
    `INSERT INTO job_events (story_id, job_id, event_type, message, payload)
     VALUES ($1, $2, $3, $4, $5::jsonb)`,
    [storyId, jobId, type, message, JSON.stringify(payload)]
  );
}

async function setStoryStatus(storyId, status) {
  await query(`UPDATE stories SET status = $2, updated_at = NOW() WHERE id = $1`, [storyId, status]);
}

async function enqueueJob(storyId, jobType, payload = {}) {
  await query(
    `INSERT INTO processing_jobs (story_id, job_type, status, payload, available_at)
     VALUES ($1, $2, 'queued', $3::jsonb, NOW())`,
    [storyId, jobType, JSON.stringify(payload)]
  );
}

async function downloadFile(story, jobId) {
  ensureDir(storagePath('originals'));
  const ext = (story.mime_type || '').includes('mp4') ? 'mp4' : 'webm';
  const output = storagePath('originals', `story_${story.id}.${ext}`);

  const res = await fetch(story.file_url);
  if (!res.ok) throw new Error(`download failed: ${res.status}`);
  const ab = await res.arrayBuffer();
  fs.writeFileSync(output, Buffer.from(ab));

  await query(
    `INSERT INTO story_assets (story_id, asset_type, file_path, mime_type, metadata)
     VALUES ($1, 'raw_video', $2, $3, $4::jsonb)`,
    [story.id, output, story.mime_type || 'application/octet-stream', JSON.stringify({ source_url: story.file_url })]
  );
  await emitJobEvent(story.id, jobId, 'downloaded', 'Source file downloaded');
}

async function createTranscript(story, jobId) {
  const text = 'Transcript placeholder generated by Module 2 worker. Replace with Whisper integration.';
  await query(
    `INSERT INTO transcript_segments (story_id, start_seconds, end_seconds, text, confidence)
     VALUES ($1, 0, 25, $2, 0.81)`,
    [story.id, text]
  );
  await query(
    `INSERT INTO story_assets (story_id, asset_type, file_path, mime_type, metadata)
     VALUES ($1, 'transcript_json', $2, 'application/json', $3::jsonb)`,
    [story.id, `generated://stories/${story.id}/transcript.json`, JSON.stringify({ language: story.language || 'as', text })]
  );
  await emitJobEvent(story.id, jobId, 'transcribed', 'Transcript generated');
}

async function createClips(story, jobId) {
  const presets = [
    ['breaking_16_9', 'Breaking Clip', 0, 90],
    ['summary_60', 'Summary 60s', 0, 60],
    ['vertical_reel_9_16', 'Vertical Reel', 0, 60],
  ];
  for (const [preset, title, start, end] of presets) {
    await query(
      `INSERT INTO generated_clips (story_id, preset, title, start_seconds, end_seconds, status)
       VALUES ($1, $2, $3, $4, $5, 'generated')`,
      [story.id, preset, title, start, end]
    );
  }
  await emitJobEvent(story.id, jobId, 'clips_generated', 'Clip presets generated');
}

async function processJob(job) {
  await query(
    `UPDATE processing_jobs
     SET status = 'running', attempt_count = attempt_count + 1, started_at = NOW(), heartbeat_at = NOW(), updated_at = NOW()
     WHERE id = $1`,
    [job.id]
  );
  await emitJobEvent(job.story_id, job.id, 'started', `${job.job_type} started`);

  try {
    const storyQ = await query(`SELECT * FROM stories WHERE id = $1`, [job.story_id]);
    const story = storyQ.rows[0];
    if (!story) throw new Error('story not found');

    if (job.job_type === 'ingest_download') {
      await setStoryStatus(story.id, 'processing');
      await downloadFile(story, job.id);
      await enqueueJob(story.id, 'transcription');
    } else if (job.job_type === 'transcription') {
      await setStoryStatus(story.id, 'transcribing');
      await createTranscript(story, job.id);
      await enqueueJob(story.id, 'clip_generation');
    } else if (job.job_type === 'clip_generation') {
      await createClips(story, job.id);
      await setStoryStatus(story.id, 'under_review');
    } else {
      throw new Error(`unknown job_type: ${job.job_type}`);
    }

    await query(
      `UPDATE processing_jobs
       SET status = 'completed', completed_at = NOW(), heartbeat_at = NOW(), updated_at = NOW(), error_log = NULL
       WHERE id = $1`,
      [job.id]
    );
    await emitJobEvent(job.story_id, job.id, 'completed', `${job.job_type} completed`);
  } catch (e) {
    const nextAvailable = new Date(Date.now() + RETRY_DELAY_MS);
    const failed = (job.attempt_count + 1) >= job.max_attempts;
    await query(
      `UPDATE processing_jobs
       SET status = $2, error_log = $3, available_at = $4, heartbeat_at = NOW(), updated_at = NOW()
       WHERE id = $1`,
      [job.id, failed ? 'failed' : 'retrying', String(e.message || e), nextAvailable]
    );
    await setStoryStatus(job.story_id, failed ? 'failed' : 'processing');
    await emitJobEvent(job.story_id, job.id, failed ? 'failed' : 'retrying', String(e.message || e));
  }
}

async function tick() {
  if (busy) return;
  busy = true;
  try {
    for (let i = 0; i < WORKER_BATCH_SIZE; i += 1) {
      const claim = await query(
        `UPDATE processing_jobs
         SET status = 'running', started_at = NOW(), heartbeat_at = NOW(), updated_at = NOW()
         WHERE id = (
           SELECT id FROM processing_jobs
           WHERE status IN ('queued', 'retrying') AND available_at <= NOW()
           ORDER BY created_at ASC
           LIMIT 1
           FOR UPDATE SKIP LOCKED
         )
         RETURNING *`
      );
      const job = claim.rows[0];
      if (!job) break;
      // reset because processJob itself will manage full transition and counts
      await query(`UPDATE processing_jobs SET status = 'queued', started_at = NULL, heartbeat_at = NULL WHERE id = $1`, [job.id]);
      await processJob(job);
    }
  } finally {
    busy = false;
  }
}

export function startWorker() {
  ensureDir(STORAGE_DIR);
  if (timer) return;
  timer = setInterval(() => {
    tick().catch(() => {});
  }, WORKER_INTERVAL_MS);
  tick().catch(() => {});
}

